
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 05 20:27:15 CST 2017
//----------------------------------------------------

package org.compi2.codigo3d.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 4;
  public static final int MENOS = 7;
  public static final int POT = 10;
  public static final int orLogico = 14;
  public static final int PAR_IZQ = 11;
  public static final int MULT = 8;
  public static final int ENTERO = 3;
  public static final int PAR_DER = 12;
  public static final int EOF = 0;
  public static final int MAS = 6;
  public static final int DIV = 9;
  public static final int RELACIONAL = 5;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int notLogico = 15;
  public static final int andLogico = 13;
}

